global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "cadvisor:8080"

  - job_name: "fastapi"
    static_configs:
      - targets:
          - "api:8000"

  - job_name: "services"
    metrics_path: /
    static_configs:
      - targets:
          - "api:8000"
          - "airflow-webserver:8080"
          - "grafana:3000"
          - "prometheus:9090"
          - "cadvisor:8080"
        labels:
          project: "alertes"